### PR TITLE
Transformed data + slice indicator

### PR DESCRIPTION
**Pull request by richtefee**
The first commit adds compatibility with transformed data (translated + scaled) and adjust the z-axis in the plot accordingly.
The second commit adds a line indicating the slider position and updates it upon changes.

Todo:
Update *.gif in README.md

### CODE REVIEW

**Comment by richtefee** [comment]
Hey,

I just checked the new merged version. It seems the slider indicator is not working correctly with images which are scaled and translated along the z-axis. Maybe you could update using an axis corrected version of "index to world coordinates" below and in second commit.
        `slice_index = event.value[0]`
        `# Convert slice index to real-world coordinates`
        `z_data_range = np.arange(*self.viewer.dims.range[0])`
        `z_data = z_data_range[slice_index]`

The problem with the current version is that the direct use of  `event.value[0]` the index and not the 'world coordinate' is used.

**Comment by MalloryWittwer** [comment]
Hey! Thanks for pointing this out. I think I might have corrected this issue lately by adding a `z_data_range` property which represents the values of the Z slider rescaled in world coordinates.

**Comment by richtefee** [comment]
Thanks a lot! I think the only small improvement would be to remove the default axis limits in x (line 106) or put its minimum not to zero but to the min of the range.
Capture
Since for shifted data this is not very convenient (see image attached). Later a plot settings menu could be a neat solution.

**Comment by MalloryWittwer** [comment]
Hey! Ok, I have made that change. Thanks for the feedback!

**Pull request closed without merging**
